### ISSUE TITLE
Need a help

### ISSUE THREAD

**Issue by dr1408** [cr4sh-me/kernel_xiaomi_surya#1]
Good evening sir I am on Poco nfc last muiu firmware with latest pixel os android 13 build and dfe .. monitor mode adapter working I have issues with internal Bluetooth 
![IMG_20240225_175404_057](https://github.com/cr4sh-me/kernel_xiaomi_surya/assets/39735654/777e27a1-0cb3-493f-8361-cac3af9fe405)
![IMG_20240225_175347_202](https://github.com/cr4sh-me/kernel_xiaomi_surya/assets/39735654/70da99a6-c999-425d-b022-f2e4ed9ffe08)

Even it show blue binder service failed all options run except when start interface it doesn't start always down any help appreciated or any way to contact you thanks in advance

**Comment by cr4sh-me** [comment]
Check out my kernel for surya, it's working 
https://xdaforums.com/t/kernel-spiderblood-nethunter-for-xiaomi-poco-x3-nfc.4571955/

**Comment by dr1408** [comment]
I am using your kernel already sir

**Comment by dr1408** [comment]
![Uploading image.jpg…]()

**Comment by dr1408** [comment]
![Uploading DBA86640-2E99-425A-B7DD-27F887B451C6.jpeg…]()

**Comment by cr4sh-me** [comment]
It looks like you were missing  some dependencies while running bt arsenal setup.
You can use my app NHLauncher to do setup and install missing dependencies or find them in here https://github.com/cr4sh-me/NHLauncher_scripts/tree/main
 (I don't remember which one)

Btw your device is surya, not karna right?

**Comment by dr1408** [comment]
Yes it's surya Poco x3 nfc .. I did airplay test wlan1 also it show injection it's on but when go to deauth in nethunter app and do sacan with wlan 1 it doesn't scan any additional steps I need ?

**Comment by cr4sh-me** [comment]
Forget about deauth in nethunter app, its not working (like most nethunter features)
Check this out https://github.com/cr4sh-me/NHLauncher
It has rewrited bt arenal so you can bind your bt interface 10x faster than in nethunter
Just run setup, wait a while and go to BT Toolkit in add-ons.
Internal bt is definitely working on surya

**Comment by dr1408** [comment]
![Screenshot_20240225-184723_NHLauncher](https://github.com/cr4sh-me/kernel_xiaomi_surya/assets/39735654/37e208b1-2e9a-46db-ad43-85675325e040)

I dunno what to setup exactly .. I went to tool kit and ran it it do scan but can't discover my iphone

**Comment by cr4sh-me** [comment]
Go to NHLauncher settings, and click "run setup" button

**Comment by dr1408** [comment]
Is there is other way or specific cause I don't want to install all tools which will take space

**Comment by cr4sh-me** [comment]
Try to run nethunter bt setup again, and check for any errors

**Comment by dr1408** [comment]
![Screenshot_20240225-190401_NetHunter_Terminal](https://github.com/cr4sh-me/kernel_xiaomi_surya/assets/39735654/9f88b36c-3b1c-48af-9c42-055d9e5bdebd)

**Comment by dr1408** [comment]
Can i contact you please cause i sold samsung and bought this phone for this feature

**Comment by cr4sh-me** [comment]
> Can i contact you please cause i sold samsung and bought this phone for this feature 

Sure, discord is r00ber.777
